stages:
  - build
  - pack
  - deploy
  
variables:
  GIT_DEPTH: "1"
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest

build:
  stage: build
  dependencies: []
  tags:
    - vs
  script:
    - cmd /c '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\msbuild.exe" ImgGen.sln /m /p:Configuration=Release'
  artifacts:
    paths:
      - bin/Release

docker:
  stage: build
  tags: 
    - docker
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build --pull --no-cache -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE

pack:
  stage: pack
  dependencies:
    - build
  tags:
    - linux
  script:
    - mkdir dist
    - cd bin/release
    - 7z a -mx9 ../../dist/ImgGen.7z *
    - cd ../..
  artifacts:
    paths:
      - dist

upload_to_minio:
  stage: deploy
  dependencies:
    - build
  tags: 
    - linux
  script:
    - aws s3 --endpoint=https://minio.mycard.moe:9000 sync dist/ s3://mycard/ImgGen
  only:
    - master

deploy_docker:
  stage: deploy
  tags: 
    - docker
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
  only:
    - master
